"""Sphinx configuration for the hypernet documentation.

The site is the WATERHYPERNET user guide; the pages are Markdown, parsed by
MyST. Layout and toolchain deliberately mirror the sibling IOPtics docs (furo
theme, ``docs/requirements.txt``, a ``.readthedocs.yaml`` at the repository
root, napoleon for numpydoc docstrings) so that the two projects stay easy to
move between. The one deliberate difference is the source format: IOPtics is
reStructuredText, this guide is Markdown. Sphinx reads both in one project, so
a future package-API section can be written either way.

.. warning::

   **The source root is ``docs/`` itself, not ``docs/source/``, so every
   ``.md`` file in this directory becomes a published page.** A file omitted
   from the toctree only raises a warning -- it is still built and still served
   at a guessable URL. Anything in here that is not meant for the public site
   must be listed in ``exclude_patterns`` below, or kept outside ``docs/``.
   That is why the Kevin Ruddick correspondence lives in ``correspondence/``
   at the repository root rather than here.
"""

import os
import sys

sys.path.insert(0, os.path.abspath('..'))

# -- Project -----------------------------------------------------------------

project = 'hypernet'
author = 'J. Xavier Prochaska'
copyright = '2026, J. Xavier Prochaska'

# -- General -----------------------------------------------------------------

extensions = [
    'myst_parser',                 # Markdown sources
    'sphinx.ext.autodoc',          # for the future package-API section
    'sphinx.ext.autosummary',
    'sphinx.ext.napoleon',         # NumPy / Google style docstrings
    'sphinx.ext.viewcode',
    'sphinx.ext.intersphinx',
    'sphinx.ext.mathjax',
]

templates_path = ['_templates']
master_doc = 'index'

# Everything in docs/ that is NOT a page of the guide. See the module warning:
# this list is the only thing standing between a stray .md file and publication.
exclude_patterns = [
    '_build',
    'Thumbs.db',
    '.DS_Store',
    'README.md',
    # Generated by whn_figures.py alongside the CSV; the same table is already
    # rendered inside choosing.md, so it must not become an orphan page.
    'summary_table.md',
]

# -- MyST --------------------------------------------------------------------

# 'linkify' is deliberately not enabled: it needs linkify-it-py, and the guide
# already writes its bare URLs as explicit <https://...> autolinks, which plain
# CommonMark handles.
myst_enable_extensions = [
    'deflist',
    'substitution',
]

# Generate anchors for h1-h3 so cross-page links such as
# `reading-many-files.md#time-and-identity` resolve.
myst_heading_anchors = 3

# -- HTML --------------------------------------------------------------------

html_theme = 'furo'
html_title = 'hypernet'
html_static_path = ['_static']

# The two CSV tables are referenced with MyST's {download} role, which copies
# them into the build. The figures under figs/ are picked up automatically as
# image references, so they need no entry here.

# -- Autodoc (unused until the package-API section exists) -------------------

autosummary_generate = True
autodoc_default_options = {
    'members': True,
    'member-order': 'bysource',
    'undoc-members': True,
    'show-inheritance': True,
}

intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),
    'numpy': ('https://numpy.org/doc/stable/', None),
    'pandas': ('https://pandas.pydata.org/docs/', None),
}
